name: Notify subscribers of new posts

on:
  workflow_run:
    workflows: ['Build and Deploy']
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: subscriber-notification
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 0 # Increase this version to clear the cache

      - name: Post-install script
        run: rake postinstall

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Notify subscribers
        run: rake notify_new_post
        env:
          API_KEY: ${{ secrets.API_KEY }}
